events {}
http {
    upstream php-quiz {
        server quiz-service:9000;
    }
    upstream php-user {
        server user-service:9000;
    }
    upstream react-front {
        server react-service:80;
    }

    # Основной прокси (порт 80)
    server {
        listen 80;

        # React
        location / {
            proxy_pass http://react-front;
            proxy_set_header Host $host;
        }
    }

    # Quiz-service (порт 8000)
    server {
        listen 8000;

        location / {
            fastcgi_pass php-quiz;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param PATH_INFO $uri;
        }
    }

    # User-service (порт 8001)
    server {
        listen 8001;

        location / {
            fastcgi_pass php-user;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param PATH_INFO $uri;
        }
    }
}
